name: Build and push ink-dev container to ECR

on:
  push:
    branches:
      - main
      - A0-1883-build-and-push-workflow
    paths-ignore:
      - '*.md'
      - 'LICENSE'

jobs:
  build-push-docker:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout Source code
        uses: actions/checkout@v2

      - name: AWS | Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: AWS | Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws/p6e8q1z1
          username: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: DOCKER | Export IMAGE_TAG
        run: |
          echo "IMAGE_TAG=`cat Makefile | grep "DOCKER_TAG :=" | awk '{print $3}'`" >> $GITHUB_ENV

      - name: DOCKER | Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1

      - name: DOCKER | Build and push latest docker image
        id: build-image
        uses: docker/build-push-action@v3
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: ./Dockerfile
          push: true
          tags: |
            public.ecr.aws/p6e8q1z1/ink-dev:${{ env.IMAGE_TAG }}
            public.ecr.aws/p6e8q1z1/ink-dev:latest
