name: Build and push docker image

on:
  push:
    paths:
      - '.github/workflows/build-and-push-image.yaml'
      - 'Dockerfile'
      - 'optimized-build.toml'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-20.04
    steps:
      - name: GIT | Checkout source code
        uses: actions/checkout@v3

      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Build and push latest docker image
        id: build-image
        env:
          RELEASE_IMAGE: public.ecr.aws/p6e8q1z1/cardinal-cryptography/ink-dev-x86_64:0.1.0
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: ${{ env.RELEASE_IMAGE }}
